In [2]:
import torch

In [3]:
a=torch.tensor([1, 2, 3])
b=torch.tensor([4, 5, 6])
c=torch.stack((a, b), dim=0)
print(c)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
print(a.shape,b.shape,c.shape)

torch.Size([3]) torch.Size([3]) torch.Size([2, 3])


In [6]:
d=torch.stack((a, b), dim=1)
print(d)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [7]:
aa=[1, 2, 3]
aa.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [8]:
bb=[4, 5, 6]
cc=torch.stack(aa)

TypeError: expected Tensor as element 0 in argument 0, but got int

In [9]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np

# 设置参数
batch_size = 8
channels = 2
h, w = 16, 16
window_size = 2
stride = window_size  # stride = 2

# 创建示例输入张量
# 为了让数据更有意义，我们创建有规律的数据
input_tensor = torch.zeros(batch_size, channels, h, w)

# 填充一些有规律的数据以便观察
for b in range(batch_size):
    for c in range(channels):
        # 在每个通道创建渐变图案
        for i in range(h):
            for j in range(w):
                input_tensor[b, c, i, j] = b * 100 + c * 10 + i * w + j

print(f"输入张量形状: {input_tensor.shape}")  # [8, 2, 16, 16]

# 创建 Unfold 实例
unfold = nn.Unfold(kernel_size=window_size, stride=stride)
unfolded = unfold(input_tensor)

print(f"Unfold 输出形状: {unfolded.shape}")  
# 应该输出: [8, 8, 64] 
# 解释: 
# - 8 = batch_size
# - 8 = channels * window_size * window_size = 2 * 2 * 2
# - 64 = 窗口总数 = (16/2) * (16/2) = 8 * 8

输入张量形状: torch.Size([8, 2, 16, 16])
Unfold 输出形状: torch.Size([8, 8, 64])


In [10]:
# 参数说明
print("\n=== 数据结构说明 ===")
print(f"每个窗口的展平向量长度: {channels * window_size * window_size} = 8")
print(f"窗口总数: {(h//stride) * (w//stride)} = 64")
print(f"窗口排列: 8行 × 8列")

# 读取示例
sample_idx = 0      # 第1个样本
channel_idx = 1     # 第2个通道
window_idx = 10     # 第11个窗口

# 计算每个通道的像素数
pixels_per_channel = window_size * window_size  # = 4

# 该通道在展平向量中的起始和结束位置
start = channel_idx * pixels_per_channel
end = (channel_idx + 1) * pixels_per_channel

# 读取数据
channel_data = unfolded[sample_idx, start:end, window_idx]

print(f"\n=== 读取示例 ===")
print(f"样本 {sample_idx}, 通道 {channel_idx}, 窗口 {window_idx}")
print(f"读取的数据形状: {channel_data.shape}")  # [4]
print(f"读取的数据: {channel_data}")

# 重塑为2x2窗口
window_2d = channel_data.reshape(window_size, window_size)
print(f"重塑为 {window_size}x{window_size} 窗口:")
print(window_2d)


=== 数据结构说明 ===
每个窗口的展平向量长度: 8 = 8
窗口总数: 64 = 64
窗口排列: 8行 × 8列

=== 读取示例 ===
样本 0, 通道 1, 窗口 10
读取的数据形状: torch.Size([4])
读取的数据: tensor([46., 47., 62., 63.])
重塑为 2x2 窗口:
tensor([[46., 47.],
        [62., 63.]])
